// <auto-generated />
using System;
using Edzoterem_adatbazis;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Edzoteremadatbazis.Migrations
{
    [DbContext(typeof(Edzoterem_adatbazisDBContext))]
    [Migration("20230127203129_GYMDB")]
    partial class GYMDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Edzoterem_adatbazis.Maganedzo", b =>
                {
                    b.Property<int>("MaganedzoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaganedzoID"));

                    b.Property<string>("MaganedzoEdzesProgram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaganedzoNev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaganedzoTagok_Szama")
                        .HasColumnType("int");

                    b.HasKey("MaganedzoID");

                    b.ToTable("Maganedzok");
                });

            modelBuilder.Entity("Edzoterem_adatbazis.Recepcios", b =>
                {
                    b.Property<int>("RecepciosID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecepciosID"));

                    b.Property<string>("RecepciosNev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecepciosNorma")
                        .HasColumnType("int");

                    b.Property<string>("RecepciosProgram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecepciosID");

                    b.ToTable("Recepciosok");
                });

            modelBuilder.Entity("Edzoterem_adatbazis.Tagok", b =>
                {
                    b.Property<int>("TagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagID"));

                    b.Property<int>("MagandedzoID")
                        .HasColumnType("int");

                    b.Property<int>("TagMagassag")
                        .HasColumnType("int");

                    b.Property<string>("TagNev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tag_SzekrenySzam")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tag_lejarati_datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("TagsagID")
                        .HasColumnType("int");

                    b.HasKey("TagID");

                    b.HasIndex("TagsagID");

                    b.ToTable("Tagok");
                });

            modelBuilder.Entity("Edzoterem_adatbazis.Tagsag", b =>
                {
                    b.Property<int>("TagsagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagsagID"));

                    b.Property<string>("TagsagTipus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TagsagID");

                    b.ToTable("Tagsagok");
                });

            modelBuilder.Entity("Edzoterem_adatbazis.Takarito", b =>
                {
                    b.Property<int>("TakaritoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TakaritoID"));

                    b.Property<string>("TakaritoNev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TakaritoNorma")
                        .HasColumnType("int");

                    b.Property<string>("TakaritoProgram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TakaritoID");

                    b.ToTable("Takaritok");
                });

            modelBuilder.Entity("Edzoterem_adatbazis.Tagok", b =>
                {
                    b.HasOne("Edzoterem_adatbazis.Tagsag", "Tagsagok")
                        .WithMany()
                        .HasForeignKey("TagsagID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tagsagok");
                });
#pragma warning restore 612, 618
        }
    }
}
